name: Deploy React App to User Site

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install

      - run: npm run build

      - name: Copy build to root
        run: |
          rm -rf * .[^.]*         # careful: this deletes current root files
          cp -r build/* .
          rm -rf build
          
      - name: Commit and push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy React build"
          git push origin main --force
